name: create memos weekly

on:
  workflow_dispatch:
  schedule:
    - cron: "5 0 * * 6"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Configure pip caching
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install python dependencies
        run: |
          python -m pip install -r requirements.txt

      - name: Fetch News
        run: |-
          python memos.py weekly
